export const enum Channel {
    Bot = "channel:bot",
    EditCommercial = "channel:edit:commercial",
    ManageAds = "channel:manage:ads",
    ManageBroadcast = "channel:manage:broadcast",
    ManageClips = "channel:manage:clips",
    ManageExtensions = "channel:manage:extensions",
    ManageGuestStar = "channel:manage:guest_star",
    ManageModerators = "channel:manage:moderators",
    ManagePolls = "channel:manage:polls",
    ManagePredictions = "channel:manage:predictions",
    ManageRaids = "channel:manage:raids",
    ManageRedemptions = "channel:manage:redemptions",
    ManageSchedule = "channel:manage:schedule",
    ManageVideos = "channel:manage:videos",
    ManageVips = "channel:manage:vips",
    Moderate = "channel:moderate",
    ReadAds = "channel:read:ads",
    ReadCharity = "channel:read:charity",
    ReadEditors = "channel:read:editors",
    ReadGoals = "channel:read:goals",
    ReadGuestStar = "channel:read:guest_star",
    ReadHypeTrain = "channel:read:hype_train",
    ReadPolls = "channel:read:polls",
    ReadPredictions = "channel:read:predictions",
    ReadRedemptions = "channel:read:redemptions",
    ReadStreamKey = "channel:read:stream_key",
    ReadSubscriptions = "channel:read:subscriptions",
    ReadVips = "channel:read:vips",
}

export const enum Moderator {
    ManageAnnouncements = "moderator:manage:announcements",
    ManageAutomod = "moderator:manage:automod",
    ManageAutomodSettings = "moderator:manage:automod_settings",
    ManageBannedUsers = "moderator:manage:banned_users",
    ManageBlockedTerms = "moderator:manage:blocked_terms",
    ManageChatMessages = "moderator:manage:chat_messages",
    ManageChatSettings = "moderator:manage:chat_settings",
    ManageGuestStar = "moderator:manage:guest_star",
    ManageShieldMode = "moderator:manage:shield_mode",
    ManageShoutouts = "moderator:manage:shoutouts",
    ManageSuspiciousUsers = "moderator:manage:suspicious_users",
    ManageUnbanRequests = "moderator:manage:unban_requests",
    ManageWarnings = "moderator:manage:warnings",
    Read = "moderation:read",
    ReadAutomodSettings = "moderator:read:automod_settings",
    ReadBannedUsers = "moderator:read:banned_users",
    ReadBlockedTerms = "moderator:read:blocked_terms",
    ReadChatMessages = "moderator:read:chat_messages",
    ReadChatSettings = "moderator:read:chat_settings",
    ReadChatters = "moderator:read:chatters",
    ReadFollowers = "moderator:read:followers",
    ReadGuestStar = "moderator:read:guest_star",
    ReadModerators = "moderator:read:moderators",
    ReadShieldMode = "moderator:read:shield_mode",
    ReadShoutouts = "moderator:read:shoutouts",
    ReadSuspiciousUsers = "moderator:read:suspicious_users",
    ReadUnbanRequests = "moderator:read:unban_requests",
    ReadVips = "moderator:read:vips",
    ReadWarnings = "moderator:read:warnings",
}

export const enum User {
    Bot = "user:bot",
    Edit = "user:edit",
    EditBroadcast = "user:edit:broadcast",
    ManageBlockedUsers = "user:manage:blocked_users",
    ManageChatColor = "user:manage:chat_color",
    ManageWhispers = "user:manage:whispers",
    ReadBlockedUsers = "user:read:blocked_users",
    ReadBroadcast = "user:read:broadcast",
    ReadChat = "user:read:chat",
    ReadEmail = "user:read:email",
    ReadEmotes = "user:read:emotes",
    ReadFollows = "user:read:follows",
    ReadModeratedChannels = "user:read:moderated_channels",
    ReadSubscriptions = "user:read:subscriptions",
    ReadWhispers = "user:read:whispers",
    WriteChat = "user:write:chat",
}

export const enum Generic {
    AnalyticsReadExtensions = "analytics:read:extensions",
    AnalyticsReadGames = "analytics:read:games",
    BitsRead = "bits:read",
    ClipsEdit = "clips:edit",
    EditorManageClips = "editor:manage:clips",
}